name: python_3_gpss
channels:
  - defaults
dependencies:
  - attrs=19.1.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2019.5.15
  - certifi=2019.6.16
  - colorama=0.4.1
  - cycler=0.10.0
  - decorator=4.4.0
  - defusedxml=0.6.0
  - entrypoints=0.3
  - freetype=2.9.1
  - icc_rt=2019.0.0
  - icu=58.2
  - intel-openmp=2019.4
  - ipykernel=5.1.1
  - ipython=7.7.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.13.3
  - jinja2=2.10.1
  - jpeg=9b
  - jsonschema=3.0.1
  - jupyter=1.0.0
  - jupyter_client=5.3.1
  - jupyter_console=6.0.0
  - jupyter_core=4.5.0
  - kiwisolver=1.1.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - matplotlib=3.1.0
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.0.2
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - msys2-conda-epoch=20160418
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - nose=1.3.7
  - notebook=6.0.0
  - numpy=1.16.4
  - numpy-base=1.16.4
  - openssl=1.1.1c
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.0
  - pickleshare=0.7.5
  - pip=19.1.1
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - pygments=2.4.2
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - python=3.6.9
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pywinpty=0.5.5
  - pyzmq=18.0.0
  - qt=5.9.7
  - qtconsole=4.5.2
  - scipy=1.3.0
  - send2trash=1.5.0
  - setuptools=41.0.1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.29.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tornado=6.0.3
  - traitlets=4.3.2
  - vc=14.1
  - vs2015_runtime=14.15.26706
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.4
  - widgetsnbextension=3.5.0
  - wincertstore=0.2
  - winpty=0.4.3
  - zeromq=4.3.1
  - zlib=1.2.11
  - pip:
    - gpy==1.9.8
    - gpyopt==1.2.5
    - paramz==0.9.5
    - "git+https://github.com/SheffieldML/PyDeepGP"
